### ISSUE TITLE
Reproduce performance is lower than paper

### ISSUE THREAD

**Issue by msjun23** [renll/SeqBoat#2]
Hi, thank you for publishing such great work.

I am attempting to reproduce the LRA benchmark using the scripts in the experiment directory, but I am getting lower performance than what is stated in the paper.

Do you have any idea why this might be happening?

I am using an A6000 48GB GPU.

**Comment by renll** [comment]
Hi, thanks for you interests in our works! May I know how much it is lower? If the gap is small, it can be due to the randomness of the training. You may want to try different random seeds and see if the difference is significant.

**Comment by msjun23** [comment]
Thank you for your reply. There is about a 2 percentage point difference in the LisoOps Image task compared to the paper’s table. If you remember, could you tell me the seed that was used for training? Also, it seems that the PathX task is not being trained. Could you guess the reason why?

**Comment by renll** [comment]
The seed used should be 1 if I remembered correctly. I think the script used for training on PathX is [here](https://github.com/renll/SeqBoat/blob/main/experiment/run_lra_pathx.sh)? Have you tried that?

**Comment by msjun23** [comment]
Yes, I ran all the experiments using the shell script in the experiment folder.

**Comment by renll** [comment]
Hmmm, so why PathX is not trained? I am not sure I understand your question clearly.

**Comment by msjun23** [comment]
I have no idea why PathX is not trained. I'll try it with seed 1 as you mentioned. Thx!
